In [3]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

import numpy as np

# Create a NumPy array representing daily temperatures for a month
temperatures = np.array([18, 22, 20, 19, 21, 25, 24, 23, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])
print("Daily temperatures:")
print(temperatures)

# Reshape into weeks (assuming 5 weeks with 6 days each)
weeks = temperatures.reshape(5, 6)
print("Weekly temperatures:")
print(weeks)

# Calculate weekly averages
weekly_averages = np.mean(weeks, axis=1)
print("Weekly averages:")
print(weekly_averages)

Daily temperatures:
[18 22 20 19 21 25 24 23 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41
 42 43 44 45 46 47]
Weekly temperatures:
[[18 22 20 19 21 25]
 [24 23 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]
Weekly averages:
[20.83333333 26.16666667 32.5        38.5        44.5       ]
