In [3]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
arr = np.random.randint(1, 101, (3, 3))
print("Original array:")
print(arr)

# Interchange rows and columns (transpose)
arr_transposed = arr.T
print("Transposed array:")
print(arr_transposed)

Original array:
[[74 90 84]
 [22 73 93]
 [43 89 74]]
Transposed array:
[[74 22 43]
 [90 73 89]
 [84 93 74]]
