In [2]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

# Generate a 1D NumPy array with 10 elements
arr = np.arange(1, 11)
print("Original array:")
print(arr)

# Reshape into a 2x5 array
arr_2x5 = arr.reshape(2, 5)
print("Reshaped to 2x5 array:")
print(arr_2x5)

# Reshape into a 5x2 array
arr_5x2 = arr.reshape(5, 2)
print("Reshaped to 5x2 array:")
print(arr_5x2)

Original array:
[ 1  2  3  4  5  6  7  8  9 10]
Reshaped to 2x5 array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reshaped to 5x2 array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
