In [1]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

# Create a 4x4 NumPy array with random float values
arr = np.random.rand(4, 4)
print("Original array:")
print(arr)

# Add a border of zeros around it
arr_padded = np.pad(arr, 1, mode='constant')
print("Padded array:")
print(arr_padded)

Original array:
[[0.98056562 0.46256724 0.29640943 0.51466599]
 [0.14005907 0.05354127 0.19602229 0.21442713]
 [0.18974495 0.36899269 0.55026242 0.18923173]
 [0.6533557  0.66233153 0.77736882 0.36303901]]
Padded array:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.98056562 0.46256724 0.29640943 0.51466599 0.        ]
 [0.         0.14005907 0.05354127 0.19602229 0.21442713 0.        ]
 [0.         0.18974495 0.36899269 0.55026242 0.18923173 0.        ]
 [0.         0.6533557  0.66233153 0.77736882 0.36303901 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
