In [1]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)

print("Element-wise addition:")
print(arr1 + arr2)

print("Element-wise subtraction:")
print(arr1 - arr2)

print("Element-wise multiplication:")
print(arr1 * arr2)

print("Element-wise division:")
print(arr1 / arr2)

Array 1:
[[1 2]
 [3 4]]
Array 2:
[[5 6]
 [7 8]]
Element-wise addition:
[[ 6  8]
 [10 12]]
Element-wise subtraction:
[[-4 -4]
 [-4 -4]]
Element-wise multiplication:
[[ 5 12]
 [21 32]]
Element-wise division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
