In [1]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

import numpy as np

arr = np.eye(5)
print("Identity matrix:")
print(arr)

print("Diagonal elements:")
print(np.diag(arr))

Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal elements:
[1. 1. 1. 1. 1.]
